#!/usr/bin/env python
"""Was the far-reach region a POLICY failure, or is the task itself marginal there?

The motion planner is an independent oracle for that question. It has full
state access and no perception problem, so a state it cannot solve is a
property of the state, not of the policy.

The demos give us its verdict for free. mani_skill/examples/motionplanning/
panda/run.py runs `seed = start_seed` (0), `solve(env, seed=seed)`, `seed += 1`
per attempt, and under --only-count-success a failed attempt calls
flush_trajectory(save=False) and moves on. So the recorded seeds are exactly
the seeds the planner SOLVED, and every gap in the sequence is a seed it could
not. Joining those gaps against the seed index turns "is the far region
reachable?" into a table lookup.

  python t2/demo_feasibility.py $MS_ASSET_DIR/demos/StackCube-v1/motionplanning/trajectory.json \\
         --index t2/results/seeds.csv

Note these are the DEMONSTRATION seeds, i.e. the training seeds. That is
normally the thing to avoid - evaluating there measures memorisation. It is
legitimate here and only here, because what is being read off them is
feasibility, which is a property of the initial state and has nothing to do
with what the policy was trained on. Label it that way in the report so it is
not mistaken for a success rate.

Power is limited by construction: the planner fails on only a few percent of
seeds, so this can detect a strong clustering and not a weak one. Say which.
"""
import argparse
import csv
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from t2_common import REGIONS, geom_from_row, wilson  # noqa: E402


def recorded_seeds(path):
    """Seeds the planner solved, from a demo trajectory.json.

    Prefer reset_kwargs.seed (what run.py passed) and fall back to
    episode_seed (what the env actually used). For an explicitly seeded reset
    the two agree; demos generated without an explicit seed only have the
    latter, and then it is a random 32-bit number rather than a small
    consecutive one - which this detects rather than silently mis-joining.
    """
    d = json.load(open(path))
    eps = d["episodes"]
    seeds, source = [], "reset_kwargs.seed"
    for e in eps:
        s = (e.get("reset_kwargs") or {}).get("seed")
        if s is None:
            s, source = e.get("episode_seed"), "episode_seed"
        seeds.append(int(s))
    return seeds, source, d.get("env_info", {})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("trajectory_json")
    ap.add_argument("--index", default="t2/results/seeds.csv")
    ap.add_argument("--out", default="")
    a = ap.parse_args()

    seeds, source, env_info = recorded_seeds(a.trajectory_json)
    lo, hi = min(seeds), max(seeds)
    solved = set(seeds)
    print(f"  demos      {len(seeds)} episodes, seed field '{source}'")
    print(f"  env        {env_info.get('env_id', '?')} "
          f"{env_info.get('env_kwargs', {}).get('control_mode', '')}")
    print(f"  seed range {lo} .. {hi}")

    if hi - lo + 1 > 4 * len(seeds):
        sys.exit("\n!! the seeds are not a dense consecutive block, so gaps are\n"
                 "   not planner failures and this test does not apply. That\n"
                 "   happens when the demos were not generated by the motion\n"
                 "   planner's seed loop (e.g. the 'rl' demo sets).\n")

    missing = [s for s in range(lo, hi + 1) if s not in solved]
    print(f"  gaps       {len(missing)} seeds in [{lo}, {hi}] the planner did "
          f"not solve ({len(missing)/(hi-lo+1):.2%})")
    if not missing:
        print("\n  The planner solved every seed it attempted. Nothing in the")
        print("  nominal support is infeasible for a solver with full state")
        print("  access, so the far-reach failures belong to the policy.")
        return

    idx = {int(r["seed"]): r for r in csv.DictReader(open(a.index))}
    have = [s for s in missing if s in idx]
    if not have:
        sys.exit(f"!! none of the {len(missing)} failed seeds are in {a.index}; "
                 f"index that range first.")
    print(f"  indexed    {len(have)} of them are in {os.path.basename(a.index)}")

    def feats(ss):
        return [geom_from_row(idx[s]) for s in ss if s in idx]

    fail = feats(have)
    ok = feats([s for s in sorted(solved) if lo <= s <= hi])
    print(f"\n  planner-failed vs planner-solved seeds, same range:")
    print(f"    {'feature':>10}  {'failed (n=%d)' % len(fail):>16}  "
          f"{'solved (n=%d)' % len(ok):>16}")
    for k in ("dist_max", "dist_min", "face_gap", "separation"):
        if k == "separation":
            f_ = [float(idx[s]["separation"]) for s in have]
            o_ = [float(idx[s]["separation"]) for s in sorted(solved) if lo <= s <= hi]
        else:
            f_ = [x[k] for x in fail]
            o_ = [x[k] for x in ok]
        print(f"    {k:>10}  {sum(f_)/len(f_)*1000:16.1f}  {sum(o_)/len(o_)*1000:16.1f}   mm (mean)")

    # The question in the form it is actually asked: of the seeds sitting in
    # the far-reach band, what fraction did the planner fail? If that is at the
    # base rate, the band is feasible and the policy owns those failures.
    print(f"\n  planner failure rate by reach band:")
    print(f"    {'band':>22}  {'n':>6}  {'failed':>7}  {'rate':>7}  {'95% Wilson':>16}")
    bands = [("dist_max < 600 mm", lambda g: g["dist_max"] < 0.60),
             ("600-760 mm", lambda g: 0.60 <= g["dist_max"] < 0.76),
             ("dist_max >= 760 mm", lambda g: g["dist_max"] >= 0.76)]
    for lab, sel in bands:
        inb = [s for s in range(lo, hi + 1) if s in idx and sel(geom_from_row(idx[s]))]
        k = sum(1 for s in inb if s not in solved)
        if not inb:
            continue
        wl, wh = wilson(k, len(inb))
        print(f"    {lab:>22}  {len(inb):6d}  {k:7d}  {k/len(inb):7.3f}  "
              f"[{wl:.3f}, {wh:.3f}]")
    # The reach bands above are a coarse slice. The question that actually
    # matters is whether the seeds in each TARGETED region are solvable, since
    # those are the regions the report attributes to the policy. A mode whose
    # planner-failure rate is at the base rate is a policy failure; one that
    # spikes is partly the task, and has to be reported that way.
    print(f"\n  planner failure rate INSIDE each targeted failure mode:")
    print(f"    {'mode':>22}  {'n':>6}  {'failed':>7}  {'rate':>7}  {'95% Wilson':>16}")
    base_k = len(missing)
    base_n = hi - lo + 1
    bl, bh = wilson(base_k, base_n)
    print(f"    {'ALL seeds (base rate)':>22}  {base_n:6d}  {base_k:7d}  "
          f"{base_k/base_n:7.3f}  [{bl:.3f}, {bh:.3f}]")
    for tag, sel in REGIONS.items():
        inb = [s_ for s_ in range(lo, hi + 1)
               if s_ in idx and sel(geom_from_row(idx[s_]))]
        if not inb:
            continue
        k = sum(1 for s_ in inb if s_ not in solved)
        wl, wh = wilson(k, len(inb))
        note = ""
        if wl > base_k / base_n:
            note = "  <- ELEVATED: partly task infeasibility, not policy"
        print(f"    {tag:>22}  {len(inb):6d}  {k:7d}  {k/len(inb):7.3f}  "
              f"[{wl:.3f}, {wh:.3f}]{note}")
    print("    A mode whose interval excludes the base rate is not purely a")
    print("    policy failure. Say so rather than reporting its success rate")
    print("    as though the task were solvable everywhere inside it.")

    print("\n  If the >=760 mm rate is at the others' rate, the far region is")
    print("  FEASIBLE and its low policy success is a policy failure - a real")
    print("  T-II mode. If it spikes, that band is partly task infeasibility")
    print("  and must be reported as such rather than as a policy weakness.")
    print("  The planner fails rarely, so this detects a strong clustering and")
    print("  not a weak one; quote the intervals, not the point estimates.")

    if a.out:
        with open(a.out, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["seed", "planner_solved", "dist_max", "dist_min",
                        "face_gap", "separation"])
            for s in range(lo, hi + 1):
                if s not in idx:
                    continue
                g = geom_from_row(idx[s])
                w.writerow([s, int(s in solved), g["dist_max"], g["dist_min"],
                            g["face_gap"], idx[s]["separation"]])
        print(f"\nwrote {a.out}")


if __name__ == "__main__":
    main()
